#!/usr/bin/env groovy
pipeline {
    agent any
    stages {
        stage('Start VM WORK') {
            agent{
                label'POWER'
            } 
            steps{
                sh 'echo "Start VM WORK"'
                sh '/usr/bin/virsh -c qemu:///system start WORK'
            }
        }        
        stage ('verify the VM is running') {
            agent{
                label 'POWER'
            }
            steps{
                sh 'ping 192.168.0.112'
            }
        }
        stage('Update time clock') {
            agent{
                label 'WORK'
            }
            steps{
                cmd 'W32tm /resync /force'
            }
        }
    }
}