#!/usr/bin/env groovy
pipeline {
    agent {
        label 'POWER'
    }
    stages {
        stage('start VM') {
            steps {
                sh 'virsh -c qemu:///system start WORK'
            }
        }
        stage ('verify the VM is running') {
            steps {
                ping '192.168.0.112'
            }
        }
    }
    node {
        label 'WORK'
    }
    stages {
        stage('Update time clock') {
            steps {
                cmd 'W32tm /resync /force'
            }
        }
    }
}